---
- name: clear cluster_hosts_name
  file: path=cluster_hosts_name state=absent
  tags:
    - create_ceph_cluster

- name: echo hosts name to file
  shell: echo -n "{{ item }} " >> cluster_hosts_name
  with_items:
    - "{{ groups['controller'] }}"
  tags:
    - create_ceph_cluster

- name: register hosts name
  shell: cat cluster_hosts_name
  register: ceph_cluster_hosts
  tags:
    - create_ceph_cluster
    - echo_hosts

- name: create ceph cluster
  shell: cd {{ ceph_cluster_dir }} && ceph-deploy new {{ ceph_cluster_hosts.stdout_lines[0] }}
  with_items:
    - "{{ groups['controller'] }}"
  tags:
    - create_ceph_cluster

- name: install ceph for every nodes includes jumpserver
  shell: cd {{ ceph_cluster_dir }} && ceph-deploy install {{ ceph_cluster_hosts.stdout_lines[0]}}

- name: create monitor node in controller group
  shell: cd {{ ceph_cluster_dir }} && ceph-deploy mon create {{ ceph_cluster_hosts.stdout_lines[0] }}

- name: gather keys from mon nodes
  shell: cd {{ ceph_cluster_dir }} && ceph-deploy gatherkeys {{ ceph_cluster_hosts.stdout_lines[0] }}

- name: create admin node
  shell: cd {{ ceph_cluster_dir }} && ceph-deploy admin {{ ceph_cluster_hosts.stdout_lines[0] }}

- name: copy create_osd.sh to host1
  copy: src=create_osd.sh dest=~/create_osd.sh mode=0777
  tags:
    - create_osd

- name: copy create_osd.sh to other nodes
  shell: scp -o StrictHostKeyChecking=no ~/create_osd.sh {{ item }}:~/ 
  with_items:
    - "{{ groups['controller'] }}"
  tags:
    - create_osd

- name: create osd
  shell: ssh -o StrictHostKeyChecking=no -t {{ item }} "~/create_osd.sh"
  with_items:
    - "{{ groups['controller'] }}"
  tags:
    - create_osd

- name: prepare create osd
  shell: cd {{ ceph_cluster_dir }} && ceph-deploy --overwrite-conf osd prepare {{ item }}:/var/local/osd
  with_items:
    - "{{ groups['controller'] }}"
  tags:
    - create_osd


- name: activate osd
  shell: cd {{ ceph_cluster_dir }} && ceph-deploy osd activate {{ item }}:/var/local/osd
  with_items:
    - "{{ groups['controller'] }}"
  tags:
    - create_osd
